name: Firebase Deploy

on:
  push:
    branches:
      - master  # メインブランチが変更されたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Node.jsのバージョンを18に設定

    - name: Install dependencies
      run: yarn install

    - name: Build the project
      run: yarn build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set up Firebase service account
      run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > "${{ github.workspace }}/firebase-service-account.json"

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-service-account.json" >> $GITHUB_ENV

    - name: Install functions dependencies
      working-directory: ./functions
      run: yarn install

    - name: Deploy to Firebase
      run: firebase deploy --only hosting,functions
